package tn.esprit.propnetapp.realestatellisting;

public class TemplateMail {

    public static String ContentMailToRecipient (String RecipientName,Integer id){
        String template = "<body style=\"margin: 0; padding: 0;\" bgcolor=\"#eaeced\">\n"
                + "  <table style=\"min-width: 320px;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#eaeced\">\n"
                + "    <tr>\n"
                + "      <td class=\"wrapper\" style=\"padding: 0 10px;\">\n"
                + "        <table data-module=\"module-3\" data-thumb=\"thumbnails/03.png\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "          <tr>\n"
                + "            <td data-bgcolor=\"bg-module\" bgcolor=\"#eaeced\">\n"
                + "              <table class=\"flexible\" width=\"600\" align=\"center\" style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                <tr>\n"
                + "                  <td class=\"img-flex\">\n"
                + "                    <img src=\"https://www.immo-salon.com/media/images/gallery/2/big/217.jpg?1684281600020\" style=\"vertical-align: top;\" width=\"600\" height=\"249\" alt=\"\" />\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "                <tr>\n"
                + "                  <td data-bgcolor=\"bg-block\" class=\"holder\" style=\"padding: 65px 60px 50px;\" bgcolor=\"#f9f9f9\">\n"
                + "                    <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                      <tr>\n"
                + "                        <td data-color=\"title\" data-size=\"size title\" data-min=\"20\" data-max=\"40\" data-link-color=\"link title color\" data-link-style=\"text-decoration:none; color:#292c34;\" class=\"title\" align=\"center\" style=\"font: 30px/33px Arial, Helvetica, sans-serif; color: #292c34; padding: 0 0 24px;\">\n"
                + "                          Dear " + RecipientName + ",\nCongratulations on your new home!\n"
                + "                        </td>\n"
                + "                      </tr>\n"
                + "                      <tr>\n"
                + "                        <td data-color=\"text\" data-size=\"size text\" data-min=\"10\" data-max=\"26\" data-link-color=\"link text color\" data-link-style=\"font-weight:bold; text-decoration:underline; color:#40aceb;\" align=\"center\" style=\"font: 16px/29px Arial, Helvetica, sans-serif; color: #888; padding: 0 0 21px;\">\n"
                + "                          This house offers a fantastic deal and is perfect for you. Don't miss out on this opportunity. Contact us for more details.\n"
                + "                        </td>\n"
                + "                      </tr>\n"
                + "                      <tr>\n"
                + "                        <td data-color=\"text\" data-size=\"size text\" data-min=\"10\" data-max=\"26\" data-link-color=\"link text color\" data-link-style=\"font-weight:bold; text-decoration:underline; color:#40aceb;\" align=\"center\" style=\"font: 16px/29px Arial, Helvetica, sans-serif; color: #888; padding: 0 0 21px;\">\n"
                + "                          <!-- Your HTML code snippet goes here -->\n"
                + "                          <tr>\n"
                + "                            <td style=\"padding:0 0 20px;\">\n"
                + "                              <table width=\"134\" align=\"center\" style=\"margin:0 auto;\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                                <tr>\n"
                + "                                  <td data-bgcolor=\"bg-button\" data-size=\"size button\" data-min=\"10\" data-max=\"16\" class=\"btn\" align=\"center\" style=\"font:12px/14px Arial, Helvetica, sans-serif; color:#f8f9fb; text-transform:uppercase; mso-padding-alt:12px 10px 10px; border-radius:2px;\" bgcolor=\"#f5ba1c\">\n"
                + "                                    <a target=\"_blank\" style=\"text-decoration:none; color:#f8f9fb; display:block; padding:12px 10px 10px;\" href=\"http://localhost:4200/admin/annonce/listAnnonces/detail/" + id + "\">Learn More</a>\n"
                + "                                  </td>\n"
                + "                                </tr>\n"
                + "                              </table>\n"
                + "                            </td>\n"
                + "                          </tr>\n"
                + "                          <!-- End of your HTML code snippet -->\n"
                + "                        </td>\n"
                + "                      </tr>\n"
                + "                    </table>\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "              </table>\n"
                + "            </td>\n"
                + "          </tr>\n"
                + "        </table>\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </table>\n"
                + "</body>\n";

        return template;
    }
}
